### ISSUE TITLE
On mobile removing number from amount input results in NaN

### ISSUE THREAD

**Issue by shawnpotter** [shawnpotter/starfield-tool#9]
When using mobile to change the quantity of a module in the Outpost Calculator. Removing the number from the input results in a NaN result in the resource list until a new number is put down. Need to have it default to 0 if possible. The resource with an Amount of NaN will stay in the list until the input is fixed or new module being added ups the amount of said resource.

**Comment by ShawnPotter** [comment]
Not a big problem, resolve after completing [Mobile-pass-2 branch](https://github.com/ShawnPotter/starfield-tool/tree/mobile-pass-2)

**Comment by ShawnPotter** [comment]
also happens on desktop
